# 分类头（Head）配置

name: kan_classification_head

# hidden_size_p/q/r 一般等于各 encoder 输出维度
hidden_size_p: 100
hidden_size_q: 100
hidden_size_r: 100

dropout: 0.5

num_labels: 2
problem_type: single_label_classification  # or "binary" 也可以再封装

use_q: true   # 是否使用实体通路
use_r: true   # 是否使用上下文通路

l2_reg: 0.0   # 额外 L2 正则（可选，通常由 optimizer.weight_decay 控制）
